global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8086']

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8082']

  - job_name: 'eventos-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eventos-service:8083']

  - job_name: 'ingressos-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ingressos-service:8081']

  - job_name: 'avaliacao-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['avaliacao-service:8084']

  - job_name: 'notifications-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['notifications-service:8085']

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8087']

  - job_name: 'webhook-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['webhook-service:8088']
