services:
  db:
    image: postgres:16-alpine
    container_name: pg-auth
    environment:
      POSTGRES_DB: auth_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d auth_service" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - backend  # Conectar na rede do compose principal

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: auth-service:dev
    container_name: auth-service
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: "8086"

      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/auth_service"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"

      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"

      EVENTS_BASE_URL: "http://host.docker.internal:8083"
      NOTIFICATIONS_BASE_URL: "http://host.docker.internal:8085"
      
      # ===================================
      # Configurações do Actuator/Prometheus
      # ===================================
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
      MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
      MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
      MANAGEMENT_METRICS_TAGS_APPLICATION: "auth-service"
      MANAGEMENT_METRICS_DISTRIBUTION_PERCENTILES_HISTOGRAM_HTTP_SERVER_REQUESTS: "true"
    ports:
      - "8086:8086"
    networks:
      - backend  # Conectar na rede do compose principal

volumes:
  pgdata:

# Usar a rede externa criada pelo docker-compose principal
networks:
  backend:
    external: true