global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'plataforma-eventos'

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API Gateway
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'api-gateway'

  # Auth Service
  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8086']
        labels:
          application: 'auth-service'

  # User Service
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']
        labels:
          application: 'user-service'

  # Eventos Service
  - job_name: 'eventos-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          application: 'eventos-service'

  # Ingressos Service
  - job_name: 'ingressos-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          application: 'ingressos-service'

  # Avaliacao Service
  - job_name: 'avaliacao-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal8084']
        labels:
          application: 'avaliacao-service'

  # Notifications Service
  - job_name: 'notifications-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8085']
        labels:
          application: 'notifications-service'

  # Payment Service
  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8087']
        labels:
          application: 'payment-service'

  # Webhook Service
  - job_name: 'webhook-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8088']
        labels:
          application: 'webhook-service'